### ISSUE TITLE
Not working on the most recent Chrome build?

### ISSUE THREAD

**Issue by ohaikai** [JoelSjogren/most#1]
Hi Joel,

Not sure if you're still actively looking at this extension, but looks like it's not working on the most recent version of chrome.

**Comment by JoelSjogren** [comment]
Thanks for your report. I will have a look in a couple of days when I get back home. Maybe the design is just too unintuitive or some viki internals changed.

**Comment by ohaikai** [comment]
> Thanks for your report. I will have a look in a couple of days when I get back home. Maybe the design is just too unintuitive or some viki internals changed.

Oh nice, glad to see you're still here. I kinda just made do without the extension as my wife wanted to watch something. I just took a peek over the js now. It might be because it's not able to grab the video window. I imagine it's failing on the InjectCueListeners, or maybe they've locked / changed their subs API / URL.

Hopefully it's an easy fix! If not I'll see if I can cut my teeth at a later time. Thank you for your time in writing the extension though!

**Comment by JoelSjogren** [comment]
It should be good now.
